name: Build apps

on:
  [push, workflow_dispatch]

jobs:
  buildnw:
    name: Build NW.js apps
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir build

      - name: Download Windows x64 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-win-x64.zip

      - name: Download Windows ia32 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-win-ia32.zip

      - name: Download Linux x64 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-linux-x64.tar.gz

      - name: Download Linux ia32 NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-linux-ia32.tar.gz

      - name: Download MacOS NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-osx-x64.zip

      - name: Extract Windows x64 NW.js
        run: unzip nwjs-v0.55.0-win-x64.zip

      - name: Extract Windows ia32 NW.js
        run: unzip nwjs-v0.55.0-win-ia32.zip

      - name: Extract Linux x64 NW.js
        run: tar -xvf nwjs-v0.55.0-linux-x64.tar.gz

      - name: Extract Linux ia32 NW.js
        run: tar -xvf nwjs-v0.55.0-linux-ia32.tar.gz

      - name: Extract MacOS NW.js
        run: unzip nwjs-v0.55.0-osx-x64.zip

      - name: Delete archives
        run: rm nwjs-v0.55.0-linux-x64.tar.gz nwjs-v0.55.0-win-x64.zip nwjs-v0.55.0-linux-ia32.tar.gz nwjs-v0.55.0-win-ia32.zip nwjs-v0.55.0-osx-x64.zip

      - name: Rename and move NW.js directories
        run: mv nwjs-v0.55.0-linux-x64 build/throbots-linux-x64 && mv nwjs-v0.55.0-win-x64 build/throbots-win-x64 && mv nwjs-v0.55.0-linux-ia32 build/throbots-linux-ia32 && mv nwjs-v0.55.0-win-ia32 build/throbots-win-ia32 && mv nwjs-v0.55.0-osx-x64/nwjs.app build/throbots.app && rm -r nwjs-v0.55.0-osx-x64

      - name: Create package.nw directories
        run: mkdir build/throbots-linux-x64/package.nw && mkdir build/throbots-win-x64/package.nw && mkdir build/throbots-linux-ia32/package.nw && mkdir build/throbots-win-ia32/package.nw && mkdir build/throbots.app/Contents/Resources/app.nw

      - name: Install dependencies
        run: npm i

      - name: Copy files to NW.js directories
        run: cp -r $(ls | grep -v build) build/throbots-linux-x64/package.nw && cp -r $(ls | grep -v build) build/throbots-win-x64/package.nw && cp -r $(ls | grep -v build) build/throbots-linux-ia32/package.nw && cp -r $(ls | grep -v build) build/throbots-win-ia32/package.nw && cp -r $(ls | grep -v build) build/throbots.app/Contents/Resources/app.nw

      - name: Rename executables
        run: mv build/throbots-linux-x64/nw build/throbots-linux-x64/throbots && mv build/throbots-linux-ia32/nw build/throbots-linux-ia32/throbots && mv build/throbots-win-x64/nw.exe build/throbots-win-x64/throbots.exe && mv build/throbots-win-ia32/nw.exe build/throbots-win-ia32/throbots.exe

      - name: Create Debian installer file structure
        run: mkdir build/throbots-debian-x64 && mkdir build/throbots-debian-x64/usr && mkdir mkdir build/throbots-debian-x64/DEBIAN && mkdir build/throbots-debian-x64/usr/bin && mkdir build/throbots-debian-x64/usr/lib && mkdir build/throbots-debian-x64/usr/share && mkdir build/throbots-debian-x64/usr/share/applications

      - name: Copy Linux build to Debian installer
        run: cp -r build/throbots-linux-x64 build/throbots-debian-x64/usr/lib

      - name: Create Symlink to command
        run: cd build/throbots-debian-x64/usr/bin && ln -s ../lib/throbots-linux-x64/throbots

      - name: Copy control file
        run: cp DEBIAN/control build/throbots-debian-x64/DEBIAN

      - name: Copy desktop file
        run: cp throbots.desktop build/throbots-debian-x64/usr/share/applications

      - name: Create Debian installer
        run: cd build && dpkg-deb --build throbots-debian-x64

      - name: Create Windows archives
        run: cd build && zip -r throbots-win-x64.zip throbots-win-x64 && zip -r throbots-win-ia32.zip throbots-win-ia32

      - name: Create Linux archives
        run: cd build && tar -czvf throbots-linux-x64.tar.gz throbots-linux-x64 && tar -czvf throbots-linux-ia32.tar.gz throbots-linux-ia32

      - name: Create MacOS archive
        run: cd build && zip -r throbots-osx.zip throbots.app

      - name: Upload Windows x64 build
        uses: actions/upload-artifact@v2
        with:
          name: throbots-win-x64.zip
          path: build/throbots-win-x64.zip

      - name: Upload Linux x64 build
        uses: actions/upload-artifact@v2
        with:
          name: throbots-linux-x64.tar.gz
          path: build/throbots-linux-x64.tar.gz

      - name: Upload Windows ia32 build
        uses: actions/upload-artifact@v2
        with:
          name: throbots-win-ia32.zip
          path: build/throbots-win-ia32.zip

      - name: Upload Linux ia32 build
        uses: actions/upload-artifact@v2
        with:
          name: throbots-linux-ia32.tar.gz
          path: build/throbots-linux-ia32.tar.gz

      - name: Upload Debian installer build
        uses: actions/upload-artifact@v2
        with:
          name: throbots-debian-x64.deb
          path: build/throbots-debian-x64.deb

      - name: Upload MacOS build
        uses: actions/upload-artifact@v2
        with:
          name: throbots-osx.zip
          path: build/throbots-osx.zip
